### ISSUE TITLE
Quick Question 

### ISSUE THREAD

**Issue by oneEyedSunday** [duccl/workdays_api#2]
Hello duccl

Saw some of your commits on apidocs and explored your profile.

Im curious as to why you're keeping the `bin` folder in source control here?

**Comment by duccl** [comment]
Hello @oneEyedSunday !

I thought it was necessary to publish in Heroku.
But seeing the docs and files of the Heroku [buildpack](https://github.com/jincod/dotnetcore-buildpack) used, the bin folder is not necessary.

I will update the repo,  thanks for your time, interest and question!

**Comment by oneEyedSunday** [comment]
No problem. Would probably like to raise some PRs to some dotnet code if I
can

**Comment by duccl** [comment]
Perfect, yes you can!! 
Thanks for the interest, let's keep moving!
